# FAKTORY_PASSWORD=secret docker-compose up
#
# curl --cacert cert/localhost.crt https://:secret@localhost:443/stats
#

version: "3.8"

services:
  faktory:
    image: contribsys/faktory
    container_name: faktory
    networks:
      - faktory
    environment:
      - FAKTORY_PASSWORD=${FAKTORY_PASSWORD}
    volumes:
      - faktory-data:/var/lib/faktory
    command: /faktory -b :7419 -w :7420 -e production

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on: ['faktory']
    secrets:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    volumes:
      - ./cert:/etc/nginx/certificates/
    networks:
      - faktory
    ports:
      - 7491:7491
      - 443:443
    healthcheck:
      test: nginx -t

networks:
  faktory: { name: faktory-demo }

volumes:
  faktory-data: { name: faktory-demo-data }

secrets:
  nginx.conf:
    file: ./nginx.conf
